/*
LINEAR PROBING

Cells in the hash table are assigned to one of the three states - occupied, empty, or deleted. 
If a hash collision occurs, the table will be probed to move the record to an alternate cell that is stated as empty.

The simplest approach to resolve a collision is linear probing. In this technique,
if a value is already stored at a location generated by h(k), 
it means collision occurred then we do a sequential search to find the empty location.*/

/*_______________________________________________________________________________________________________*/


/* Here is the code and implementation */

#include <stdio.h>
#define SIZE 10
int hash(int key)
{
 return key%SIZE; }
int probe(int H[],int key)
{
 int index=hash(key);
 int i=0;
 while(H[(index+i)%SIZE]!=0)
 i++;
 return (index+i)%SIZE; }
void Insert(int H[],int key)
{
 int index=hash(key);
 
 if(H[index]!=0)
 index=probe(H,key);
 H[index]=key;
}
int Search(int H[],int key)
{
 int index=hash(key);
 
 int i=0;
 
 while(H[(index+i)%SIZE]!=key)
 i++;
 
 return (index+i)%SIZE; }
int main()
{
 int HT[10]={0};
 
 Insert(HT,12);
 Insert(HT,25);
 Insert(HT,35);
 Insert(HT,26);
 
 printf("\nKey found at %d\n",Search(HT,35));
 return 0; }